# Generated by Django 3.0 on 2019-12-19 02:49

from django.db import migrations, models
import django.db.models.deletion
import s_store_api.utils.store


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('s_store_api', '0002_auto_20191219_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='limited_customer_group',
            field=models.OneToOneField(default=s_store_api.utils.store.get_default_limited_customer_group, on_delete=django.db.models.deletion.CASCADE, related_name='customer_group_store', to='auth.Group'),
        ),
    ]
