# Generated by Django 3.0 on 2019-12-20 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('s_store_api', '0006_auto_20191219_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='staff_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_group_store', to='auth.Group'),
        ),
    ]
