# Generated by Django 3.0 on 2019-12-20 02:23

from django.db import migrations, models
import django.db.models.deletion
import s_store_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('s_store_api', '0007_store_staff_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='staff_group',
            field=models.OneToOneField(default=s_store_api.models.get_default_staff_group, on_delete=django.db.models.deletion.CASCADE, related_name='staff_group_store', to='auth.Group'),
        ),
    ]
