# Generated by Django 3.0 on 2019-12-23 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_store_api', '0009_auto_20191223_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='s_store_api.Coin')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='s_store_api.Store')),
            ],
            options={
                'unique_together': {('store', 'coin')},
            },
        ),
    ]
